package org.java.designpatterns.visitor.computer;

import org.apache.log4j.Logger;

/**
 * Created by mgupta on 1/24/17.
 */
public class ComputerPartDescriptionVisitor implements ComputerPartVisitor {

    private static final Logger LOGGER = Logger.getLogger(ComputerPartDisplayVisitor.class);

    @Override
    public void visit(Computer computer) {
        LOGGER.info("Computer : an electronic device for storing and processing data, typically in binary form, according to instructions given to it in a variable program");
    }

    @Override
    public void visit(Mouse mouse) {
        LOGGER.info("Mouse : an input device to instruct computer");
    }

    @Override
    public void visit(Keyboard keyboard) {
        LOGGER.info("Keyboard : a panel of keys that operate a computer");
    }

    @Override
    public void visit(Monitor monitor) {
        LOGGER.info("Monitor : A device to display the video and graphics information generated by the computer");
    }
}
